### PR TITLE
resources with no url/file are safe

### PR DESCRIPTION
**Pull request by wardi**

### CODE REVIEW

**Comment by wardi** [comment]
@JVickery-TBS I've submitted this one upstream, can wait to see what they say but it should be safe to merge

**Comment by JVickery-TBS** [comment]
@wardi should we raise an actual error here or return a certain status code and error message? Not sure what the security extension `before_update` and `before_create` does :/

**Comment by wardi** [comment]
They're called by endpoints that can raise validation errors, but raising validation errors the way ckanext-security does here isn't great: it doesn't combine errors with errors from other fields (because it's not run as part of the schema) and seems to invent field names for some reason.

This was the minimal fix I could come up with that allows resources to not have a url set or file uploaded.

**Comment by JVickery-TBS** [comment]
https://github.com/open-data/ckanext-security/pull/3 upstream cherry-pick

**Pull request closed without merging**
